query {
    allMembers {
        edges {
            node {
                name
                title
                description
                picture
                socials {
                    platform
                    displayname
                    link
                }
            }
        }
    }
}
